name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - portal/**
      - solution/**
  workflow_run:
    workflows:
      - Commit Portal
      - Commit Solution
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build_solution:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: ${{ runner.temp }}/solution.zip
          solution-folder: solution
          solution-type: Managed

      - uses: actions/upload-artifact@v2
        with:
          name: solution
          path: ${{ runner.temp }}/solution.zip

  build_portal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: portal
          path: portal

  deploy:
    needs:
      - build_solution
      - build_portal
    environment: production
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/download-artifact@v2
        with:
          name: solution
          path: ${{ runner.temp }}

      - uses: actions/download-artifact@v2
        with:
          name: portal
          path: ${{ runner.temp }}

      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.APPLICATION_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: ${{ runner.temp }}/solution.zip
          run-asynchronously: true

      - name: Authenticate to Dataverse
        run: |
          pac/pac auth create `
            --url $env:URL `
            --applicationId $env:APPLICATION_ID `
            --clientSecret $env:CLIENT_SECRET `
            --tenant $env:TENANT_ID `
            --cloud Public
        env:
          URL: ${{ secrets.URL }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        shell: powershell

      - name: Import portal
        run: |
          pac/pac paportal upload `
            --path ${{ runner.temp }}/portal/starter-portal
        shell: powershell
