name: Provision Dev

on:
  workflow_dispatch:

jobs:
  build_solution:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: ${{ runner.temp }}/solution.zip
          solution-folder: solution
          solution-type: Unmanaged

      - uses: actions/upload-artifact@v2
        with:
          name: solution
          path: ${{ runner.temp }}/solution.zip

  deploy:
    needs: build_solution
    environment: development
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/download-artifact@v2
        with:
          name: solution

      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.APPLICATION_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: solution.zip
          run-asynchronously: true

      - name: Authenticate to Dataverse
        run: |
          pac/pac auth create `
            --url $env:URL `
            --applicationId $env:APPLICATION_ID `
            --clientSecret $env:CLIENT_SECRET `
            --tenant $env:TENANT_ID `
            --cloud Public
        env:
          URL: ${{ secrets.URL }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
        shell: powershell

      - name: Import portal
        run: |
          pac/pac paportal upload `
            --path portal/starter-portal
        shell: powershell
